### ISSUE TITLE
Add HTML5 Button

### ISSUE THREAD

**Issue by ThatOneGuyDotNet** [ThatOneGuyDotNet/QuickJava#23]

**Comment by ThatOneGuyDotNet** [comment]
The list of HTML5 media types that FF supports is ever expanding, too many to add one for each button and toggling them all at the same time is not ideal.  Hopefully other extensions will be a better fit for this (there are already some geared towards disabling HTML5 on Youtube which is prob one of the highest usecases for this feature)

**Comment by Gitoffthelawn** [comment]
I concur.  It's no longer realistic to toggle HTML5 as a whole.
