### ISSUE TITLE
Style deactivation not saved

### ISSUE THREAD

**Issue by staudenmeir** [ThatOneGuyDotNet/QuickJava#25]
I use Firefox version 41.0.1 on Windwos 8.1. When I disable "Style" it only works in the active tab, but not in new tabs. The other options work fine.

**Comment by Gitoffthelawn** [comment]
If @staudenmeir means "CSS" when he/she says "Style", it still, after the new release of v2.1.0, only applies to the current tab.

Only applying to the current tab seems more desirable in most cases, but is different from, say, how the JS button behaves.

**Comment by ThatOneGuyDotNet** [comment]
Hmm, maybe I read this wrong but I was thinking it was an extension of the bug with the button status not being reset when switching tabs (so if you went to a new tab where it was on and clicked the button, currently displaying off status, it would switch it to off)

**Comment by Gitoffthelawn** [comment]
Ya, one of us is reading it wrong. :)

Either way, I like the current behavior.  I think, on the other hand, @staudenmeir either wants CSS toggling to work on all tabs, or simply expected it to do so.

**Comment by ThatOneGuyDotNet** [comment]
If that is what the original request meant then it would be filed under 'enhancements' and 'wontfix' rather than 'bug'... and still closed.  Sorry staudenmeir.

**Comment by staudenmeir** [comment]
I thought it was a bug that disabling "Style" only affected the active tab (since e.g. "JavaScript" affects all tabs).

**Comment by Gitoffthelawn** [comment]
Thanks for clearing it up @staudenmeir .

Doug, you owe me a... oh wait, we didn't bet on it.

**Comment by ThatOneGuyDotNet** [comment]
Git: Here's a thumbs up, how's that?

Staudenmeir: Turning off CSS for all tabs doesn't make much sense to me, and it definitely behaves differently because it's a per-tab setting in FireFox itself.  Sorry for the confusion.
