### ISSUE TITLE
QuickJava Error in Browser Console

### ISSUE THREAD

**Issue by Gitoffthelawn** [ThatOneGuyDotNet/QuickJava#27]
Receiving the following error in the Browser Console in Firefox v42.0 when using QuickJava v2.0.6.1:

>  [QuickJava]: An exception occurred in the QuickJava script. Error name: ReferenceError.
>  
>   Error description: undefined.
>   Error number: undefined.
>   Error message: msgAlert is not defined1 browserOverlay.js:726:49
>  
>  console.trace():1 browserOverlay.js:726
>  thatoneguydotnet.QuickJava.consoleLog() browserOverlay.js:726
>  thatoneguydotnet.QuickJava.handleError() browserOverlay.js:91
>  thatoneguydotnet.QuickJava.onLoad() browserOverlay.js:86
>  \<anonymous\> browserOverlay.js:826

**Comment by Gitoffthelawn** [comment]
Same errors in Firefox v43.0

**Comment by ThatOneGuyDotNet** [comment]
This should be resolved in V2.0.8 (Currently pending review, should be available in a day or two)
https://github.com/ThatOneGuyDotNet/QuickJava/commit/7d39daa898609331fc390dba99d03160538b6b87

**Comment by Gitoffthelawn** [comment]
Thanks!  BTW, I didn't see the error in the prior version of QuickJava when used with Firefox v45.0.1, but I did not test it nearly as thoroughly as with Firefox v43.x
