### ISSUE TITLE
Compatibility with FF-v43

### ISSUE THREAD

**Issue by Compyooter** [ThatOneGuyDotNet/QuickJava#29]
Hi there,

QuickJava doesn't work with FF43, the latest release. Will it be updated to work with FF43?

Interesting sidenote though: On a number of new installations, I couldn't add the QJ add-on to FF43, as above. The current QJ available version is 2.0.7. I also couldn't add 2.0.6 (I have the xpi file). OK. What's interesting is that I have a few other instances of FF with the QJ add-on. Those have had the add-on for a long time. Those FF instances are at the latest FF release (FF43.0.4), and QJ DOES work fine with it. QJ on all those is still at 2.0.6, and does not update to 2.0.7. I also cannot update it manually. So, to summarize: cannot add QJ to newest FF, but if FF already had QJ, it does work. Just something I noticed.

**Comment by Gitoffthelawn** [comment]
The latest release is FF44.  QuickJava v2.0.7 is coded to only work with FF44 or later.  I don't know if that was intentional or an accident.  But v2.0.6 should work with FF43 and v2.0.7 should work with FF44.

**Comment by Compyooter** [comment]
@Gitoffthelawn yup. At the time I wrote this, FF44 wasn't down the pipe yet. Updated to FF44+QJ2.0.7. Thanks.

**Comment by Gitoffthelawn** [comment]
@Compyooter You're welcome.  Glad it's working for you now!
