### ISSUE TITLE
Palemoon 26.1.1 and autoreload on change

### ISSUE THREAD

**Issue by Janaue** [ThatOneGuyDotNet/QuickJava#30]
hello,
I have discovered your module which works almost well, with palemoon 26.1.1, in version 2.0.7, but the autoreload when a setting is changed works poorly. the version 2.0.4.1-signed seems to work on this issue.

**Comment by ThatOneGuyDotNet** [comment]
Palemoon is not supported.  If you wish to update the code and submit a fork that works in FF and Palemoon then I will implement it (and credit you in the ReadMe/version history).
