### ISSUE TITLE
QJ randomly forgetting specific setting

### ISSUE THREAD

**Issue by Compyooter** [ThatOneGuyDotNet/QuickJava#31]
Hello,

Reporting an issue with QJ add-on. My QJ settings are that cookies should be on at initial load. Sometimes, at total random, QJ doesn't turn cookies on. The browser would start up with cookies turned off. In the QJ toolbar drop-down, cookies would then be unchecked.
The setting doesn't change. I double check it every time this happens. QJ remembers the settings, but doesn't actually turn cookies on.

This is the only setting that does this. All other QJ settings are reliable. As I said, this happens at random. I don't remember when I started noticing these, so I don't know if this is new to v2.0.8 or not. Current FF version is 47.0.1, but this was definitely going on with the last few version as well, i.e. 47.0 and 46.x

**Comment by ThatOneGuyDotNet** [comment]
Can you tell me how often on average this happens, about? (one out of 
every 5 starts, one of every 100?)  Issues like these that happen 
randomly and only affect one person can be difficult to track down but 
we'll give it a shot.

**Comment by Compyooter** [comment]
Hi Doug,

Thanks for looking into this.

I haven't monitored these occurrences to know it's frequency. Thinking
about it now that you ask, I estimate it's about 1 out of 10.

As you said, an issue happening at random, and is only affecting one person
can indeed be difficult to debug. Nearly nothing to go on (I ain't a dev,
but know that much). Though it is a little annoying (logins failing), it's
not really a problem. I just turn cookies on when I notice it. So please
forget about this. I greatly appreciate this great product you offer free,
and know you're always improving on it. Thank you for your work in creating
this add-on, for free.

Thanks,
Benjamin

**Comment by Gitoffthelawn** [comment]
I'll chime in that I have occasionally seen this as well.  Used to occur more often.

**Comment by Compyooter** [comment]
@Gitoffthelawn Interesting. Was it cookies for you too, or another setting? Was it consistent (i.e. the same setting)?

**Comment by Gitoffthelawn** [comment]
@Compyooter I have not seen it happen in a while, but IIRC it was either JS or cookies.  IIRC, it was consistent (the same setting).

**Comment by ThatOneGuyDotNet** [comment]
Interesting, I'm wondering if it's just one setting or all of the 
settings.  Do you have any other items (maybe Flash or Java?) that you 
normally keep on/off that you wouldn't mind switching on initial load 
and keeping an eye on it and cookies to see if both behave the same way?

-Doug

**Comment by Compyooter** [comment]
Only the cookies setting does this. JS is also set to be on at startup, and
it always is.

**Comment by Gitoffthelawn** [comment]
When I experienced it, it was just one setting as well.  All the other settings were as expected.

**Comment by ThatOneGuyDotNet** [comment]
In the latest version I am working on (2.1.0) I changed the code ever so slightly so we'll see if this fixes it.  I hope to submit it for review soon.  After it updates, please let me know if it still happens.

**Comment by Gitoffthelawn** [comment]
Thanks.  I haven't seen it happen recently, BTW.

**Comment by Compyooter** [comment]
I've had this just yesterday.
@ThatOneGuyDotNet ok. Since this happens at random, and not that frequent, it'll take at least 2 weeks to see whether it happens again or not. Will keep an eye out for this. Thank for your efforts!

**Comment by Gitoffthelawn** [comment]
@Compyooter Thanks for the update!

**Comment by ThatOneGuyDotNet** [comment]
Version 2.1.0 has been submitted for review.  There are 52 other extensions awaiting review ahead of me so it may be a while.  If you want to install the beta version and test it please do so here:
https://addons.mozilla.org/en-US/firefox/addon/quickjava/versions/2.1.0

Note: I'm not sure if installing this version will allow automatic upgrades in the future, after 2.1.0 is released you may want to verify that it says you are running the current version.  If you prefer to wait until it is released then that works too. I will be unavailable for most of next week anyway.  Have a good week!

**Comment by Compyooter** [comment]
I just had this. On this machine the addon was still v2.0.8, but I'm writing it because it had a weird twist this time. I logged in to LinkedIn. It logged on fine. After a second, it went, by itself, to a login page. I checked QJ, and cookies were off. Turned cookies on, pressed the browser's 'back' button and came back to my logged in LinkedIn.

I updated QJ to v2.1.0, but thought I should report this because of this interesting quirk. Might give a clue if this issue comes up again.

Thanks again for your great work!

**Comment by Compyooter** [comment]
Can now confirm, this is happening with v2.1.0 too.
If it's just me, and this issue is not affecting more people (as much as you know from reports), you don't need to sweat over it. Like I said earlier, when it happens, it shows itself, and is easily resolved for the session. It never happens again in a session.
Thank you, though

**Comment by Compyooter** [comment]
Happening with 2.1.2 too. Recently I started seeing that it sometimes forgets other settings, such as JS or Images, as well.
