### ISSUE TITLE
Add toggle for WebRTC

### ISSUE THREAD

**Issue by Gitoffthelawn** [ThatOneGuyDotNet/QuickJava#32]
Unfortunately, some mainstream websites are now (inexplicably) requiring WebRTC in order to function.

Most users have no need for WebRTC to be enabled a majority of the time.

Can you add a toggle for WebRTC?

**Comment by ThatOneGuyDotNet** [comment]
It looks like WebRTC is just javascript, is that correct? If so it is outside the scope of this project.  You may be able to block (most) of it with Adblock rules or NoScript?

**Comment by Gitoffthelawn** [comment]
WebRTC is enabled/disabled via the `media.peerconnection.enabled` preference.  This site contains details: https://wiki.mozilla.org/Media/WebRTC/Privacy

So toggling that pref via a QuickJava button would be simple and should be effective.

**Comment by Gitoffthelawn** [comment]
Thanks for the WebRTC button!  Works a treat.

At first, I didn't like the 3 letters crammed into a single button, and was thinking I would prefer the single letter `R` or the two letters `WR`.  It also is definitely a little wider than the other buttons.  But now I'm sorta getting used to it.

What do you think?

**Comment by ThatOneGuyDotNet** [comment]
I don't mind the (slightly) wider, better to be less confusiong, and most people will probably never even use it (hell, most won't know what it does).

**Comment by Gitoffthelawn** [comment]
> and most people will probably never even use it (hell, most won't know what it does).

I might be promoting your extension to people who want to toggle WebRTC, so it could get more popular! :)

BTW, the existing WebRTC toggling extensions have about 40,000 users between them.
