### ISSUE TITLE
Req: default settings by site

### ISSUE THREAD

**Issue by FredThompsonII** [ThatOneGuyDotNet/QuickJava#33]
How to create URL-specific settings to override the defaults?

**Comment by Gitoffthelawn** [comment]
I'm not sure if that would be within the scope of this extension, but if it is, that will be ***extremely*** useful.

**Comment by ThatOneGuyDotNet** [comment]
Sorry this is definitely outside the scope of this extension.

**Comment by Gitoffthelawn** [comment]
Fair enough. :smile:
