### ISSUE TITLE
Re-name Suggestions

### ISSUE THREAD

**Issue by ThatOneGuyDotNet** [ThatOneGuyDotNet/QuickJava#35]
With so many changes in this next version it's probably a good time to move away from "Java" being in the name.  I've needed to do it for a while but have been putting it off for several reasons, but in the next version they're making me move the preferences which is kinda a pain... so I might as well move them to the new name while I'm at it. (Don't worry, from a user perspective all preference moves will be automatic.)

This "Issue" is for anybody to join in on the discussion to suggest names.  Unfortunately I have to submit the next extension version in the next day or two to retain my featured status and I didn't think of renaming until today, so it will be a quick discussion and I apologize to any that see it too late to participate.

Goals of new name: Describe the extension (sound relevant when displaying in addon search results) and be unique enough that google searches will return my extension. 

My current thoughts:
SmoothSwitch
SlickToggle
ToogleZilla

I would love something that's a throwback to the current name but QuickToggle, QuickSwitch and anything else I have thought of just aren't unique enough.  I've also tried variations on agile, rapid and swift but those base names are too relevant in the computer world.

I'm not supper happy with any of the things I've come up with (or the ones I am are already used).  Please comment below with suggestions and/or comments on existing suggestions.  Thanks!

**Comment by Gitoffthelawn** [comment]
With the time crunch in mind, I'm working on it.

BTW, I think you meant ToggleZilla, instead of ToogleZilla above.  Although, I will say, the latter makes one smile. :smiley:

**Comment by Gitoffthelawn** [comment]
Apparently, I'm a faster worker than I realized.  How about:

***PowerToggles***

Searching for that term (with and without the terminating letter `s`) within AMO comes up nil, which is ideal.

**Comment by ThatOneGuyDotNet** [comment]
Hah, yeah... definitely meant ToggleZilla (though, also my least favorite option right now).  Power Toggles is the name of an android app already.  So while it's a good suggestion, unfortunately it's too good ;)

**Comment by ThatOneGuyDotNet** [comment]
I think I'm going to wrap up what I've got and submit it... name change in future version.  Keep any suggestions coming :)

**Comment by Gitoffthelawn** [comment]
I think if you use any common words, it's likely you will find an app, extension, website, or laundry detergent that uses the name! :)

Since you may not have submitted yet, I'll perform a real-time core dump of my stream of consciousness.  Okay, stand back and brace yourself on something sturdy...

InstaToggles
DarthToggles
QuickPower
Powgles
StuffYouMayWantToToggle
CrapYouMayNotNeed
QuickAndEasy *(no comment)*
BestToggles
TogglesDeluxe
UltraToggles
SuperToggles
JustToggles
ToggleIt
ToggleLikeWoggle
Toogles
Moogles
ManyToggles
MultiToggle
AllToggles
Toggley-doo-dah
SwissArmyToggles
Toggle-a-rama
ToggleSchmoggle
Joggles
Zoggles
Woggles
SwitchBlade
SwitchesForTheBitches
SwitchAnything
SuperSwitches
LoseTheBitchMakeTheSwitch

...okay, I better stop...

**Comment by Gitoffthelawn** [comment]
...okay, I couldn't stop...

ShakeYourToggle
Putatoggleonit _(with apologies to Beyonce)_
JustSwitches
ItsaswitchnotTwitch
RichSwitch
EverySwitch
ImRickJamesSwitch _(with apologies to Dave Chappel)_
GroovyToggles
RealToggles
QuickToggleSwitches
FeelThePower
HappyButtons
HappyToggles
WelcomeToTheToggle _(with apologies to Guns N' Roses)_
DontEatMuttonPressAButton
Buttonheaded
DougButtons
ThatOneGuyButtons

...clearly, I've finally found my calling...

**Comment by ThatOneGuyDotNet** [comment]
I think you had me at Toogles, or was it SwissArmyToggles?

ManyToggles is an actual contender though.

The re-name is still going to wait because I don't have time to re-do the "Marketing" half of it this week and want to get it all right.  Thanks for the brain dump and keep them coming!
