### ISSUE TITLE
Enhancement: Add functionality to toggle anything

### ISSUE THREAD

**Issue by Gitoffthelawn** [ThatOneGuyDotNet/QuickJava#36]
I was thinking (uh oh)... most settings are as simple as toggling a single pref.

What if this extension was extended to toggle _any_ pref?

The user would simply specify the name of the pref, the values for enabled/disabled, and what letters they want on the button.  Presto!  Now the extension is perhaps the most powerful and useful one on AMO.

**Comment by ThatOneGuyDotNet** [comment]
Can I send support requests to you? ;)

**Comment by Gitoffthelawn** [comment]
Absolutely!  I have already configured /dev/null to handle them.  ;)

LOL, seriously, it could be hidden behind an "advanced" button, if needed.  But the extension's UI is pretty confusing to novices, so I doubt they rarely do anything except click `Cancel` when they stumble into it.  Anybody mucking around in the settings already needs to be able to write regex and/or CSS, so I think providing a pref name is within their ability.

Of course, if they don't go into the extension's settings, this enhancement will be completely transparent.

**Comment by ThatOneGuyDotNet** [comment]
Will keep this open for consideration... if it does happen, it may be a while.

**Comment by Gitoffthelawn** [comment]
Sounds good.  Thanks. :)

**Comment by ZatsuneNoMokou** [comment]
This could be interesting to control `media.autoplay.enabled` that control html5 media autoplay. If you disable it, some website are much harder to play so a nice button would be great
