### ISSUE TITLE
Firefox lagging after 2.1.0 update

### ISSUE THREAD

**Issue by Gitoffthelawn** [ThatOneGuyDotNet/QuickJava#37]
Okay, I'm hesitant to post this until I have performed more research, but it might help you and could also help other users.

Since upgrading to v2.1.0, I'm experiencing some weird lagging in Firefox.  Besides upgrading this extension, the only other thing that changed was an update to another extension.

I'll be performing some testing and debugging to figure out what is going on, but I figured I would post this in case you (or others) are experiencing anything similar.

Note that I have toggled CSS several times, and since that code was changed with the release of v2.1.0, that's the most probable suspect.  That, of course, is if it has anything at all to do with this extension, which I put at well under 50%... or do I give you too much credit? :)

**Comment by ThatOneGuyDotNet** [comment]
Hmm, I'm not seeing it (FF 48) and I don't think the new version is doing anything that should cause it.  I update icons when switching tabs, other than that, same frequency but now on a slight delay to fix a display bug... stupid CSS.  I'll keep an eye out, let me know what you find.

**Comment by Gitoffthelawn** [comment]
Will do.  I doubt it is this extension, but I'll do some work to figure it out.

**Comment by Gitoffthelawn** [comment]
Will do. I doubt it is this extension, but I'll do some work to figure it out.
