### ISSUE TITLE
Enhancement: Toggle third-party cookies

### ISSUE THREAD

**Issue by Gitoffthelawn** [ThatOneGuyDotNet/QuickJava#39]
Firefox added functionality to allow/deny third-party cookies.

It will be useful if this extension has a toggle (er, toogle) to toggle third-party cookies.. 

The only catch is that Firefox allows three possibilities: _always_, _never_, and _from visited_.  I'm fine if it just toggles between _always_ and _never_.

**Comment by Gitoffthelawn** [comment]
Ping! :+1:

**Comment by ThatOneGuyDotNet** [comment]
I won't have the time to even look into this for a while.  If you would like to do the coding and a pull request then I will try to review/merge it in a timely fashion.  The setting should save the previous value and toggle between 'never' and the previous, kinda like the proxy value does. Iif set to 'never' when first used then use 'visited' as the set value, this setting not being the default implies the user has used that setting and knows what they're doing so we should use the most restrictive option.

**Comment by Gitoffthelawn** [comment]
We'll see who has more time first!  I'm overbooked, but occasionally I'll do a little project for fun to relax and get my mind off bigger issues.  But I've got a long list of commitments right now...
