### ISSUE TITLE
QuickJava not compatible with latest version of Firefox! please help!

### ISSUE THREAD

**Issue by Gohargem** [ThatOneGuyDotNet/QuickJava#40]
Hello I recently have updated my firefox to version 43 and ever since the add-on has been disabled due to incompatibility. Could you please update the add-on to make it compatible with firefox 43 and later versions? Thanks for reading.

**Comment by ThatOneGuyDotNet** [comment]
Please make sure you are using the latest version of QuickJava that is compatible with your browser.  Your browser version (43) is quite old so you will have to use QJ 2.0.6.1-signed which can be found here if you scroll down:
https://addons.mozilla.org/en-US/firefox/addon/quickjava/versions/

You must be on version 44 or newer to use the latest version of QuickJava.

**Comment by Gohargem** [comment]
Hey!

Thanks for the reply. I recently updated my firefox again, this time to v 47.0.1 and I found out QuickJava is working again! You were right my browser was old. I don't update very often. But now that I have updated again QuickJava is working well. 

Thanks for the tip :).

**Comment by ThatOneGuyDotNet** [comment]
Glad it helped!
