### ISSUE TITLE
"Temporarily allow" buttons

### ISSUE THREAD

**Issue by onpon4** [ThatOneGuyDotNet/QuickJava#43]
Hey, I was wondering if it would be possible to add "temporarily allow" buttons to this extension? I only care about this for JavaScript, but I guess if this feature were to be added it would make sense to add it for everything else too.

The behavior I propose is to leave JavaScript disabled, but reload the page in a state where JavaScript will work on that page only until the user navigates away from the page. In this way, a user would be able to keep JavaScript permanently disabled, but easily enable JavaScript for pages where it is needed on a case-by-case basis. It would be a lot safer than the alternative of enabling JavaScript, doing your work on that page, and then having to remember to disable it again before going anywhere else.

**Comment by ThatOneGuyDotNet** [comment]
Unfortunately that functionality is outside the scope of this extension as I don't do any page level functionality.  There may be better plugins that match your needs, such as NoScript, or you may find that using the QuickJava options to set the defaults on a new tab opening may meet your needs.  To get to the options right click any of the QJ icons and select "Options".  You will see a dropdown that will say something like "On 'Initial Load'" that you can change to "On 'New Tab'" and then set JavaScript to off.
