### ISSUE TITLE
WebExtensions

### ISSUE THREAD

**Issue by DaAwesomeP** [ThatOneGuyDotNet/QuickJava#44]
Is it possible to implement this awesome addon in a WebExtension? I lightly dug through the WebExtensions API and I saw nothing about enabling/disabling plugins.

**Comment by agenthardtofind** [comment]
**Doug thanks for the lovely addon**,
 whats the progress status?
Waiting  a legacy one for esr52 & pale-moon,
Web-extension for FF57

**Adding toggles for the important buttons should be possible as api's are added recently,**
    _WebGL Support_
    _WebRTC Support_
    _JavaScript toggle_ 
    _cookies toggle_ 
    _Image _ toggle_ 
    _Animated Images toggle_ 
    _CS toggle_
    _dom.storage.enabled toggle _

**QuickJava 2.1.2**
has this error
quickjava/content/browserOverlay.js

 if (window.console && window.console.log) { window.console.log('[QuickJava]: ' + msg); if (stackTrace && window.console.trace) { window.console.trace(); } }

**Comment by ThatOneGuyDotNet** [comment]
I have been working with the Mozilla Addon development team to discuss my conversion options.  Right now there is a kinda-hacky way to do it which will behave different from the current behavior. In short I will have to catch each page request and inject the settings into the header request, rather than setting a browser level setting, and it only works on http/ftp/about requests, not data: or blob: urls, which I'm not thrilled about. The chromeSettings piece I need was brought up in the last internal development meeting at the Mozilla team and the response was "it was said that offering a way to globally change settings would be easy, but other add-ons may also need site-specific settings. If there is any news about this I will let you know."

@agenthardtofind, Can you please share the information on JS/Cookies/Images/CS/WebGL/WebRTC toggling that you have?

Of course after all of the how issues are worked out, I still need to find time to put towards developing it, which is always tough.  Please note that Palemoon is not supported and I have no intentions of supporting it.  I believe one of the older versions works with Palemoon, (maybe 1.8.1?) but with less functionality.

**Comment by BillMcCloskey** [comment]
Well we are actively working on ways to bring all features to the new api, if you think anything is missing just file a bug , needinfo the triage owner or devs & 

block 

[meta] WebExtension requirements for 1&1 extensions 

https://bugzilla.mozilla.org/show_bug.cgi?id=1333828


[meta] External bugs that webextensions depends on

https://bugzilla.mozilla.org/show_bug.cgi?id=1351411

[meta] Webextensions Development


Most of the things this ext does can be done easily with WE,helped a few devs to port fix this
like these:-
https://addons.mozilla.org/en-US/firefox/addon/popup-blocker/
https://addons.mozilla.org/en-US/firefox/addon/block-images-webextensions/
https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/
https://addons.mozilla.org/en-US/firefox/addon/mute-tab-webextension/
https://addons.mozilla.org/en-US/firefox/addon/javascript-toggler/
https://addons.mozilla.org/en-US/firefox/addon/javascript-toggle-on-and-off/
https://addons.mozilla.org/en-US/firefox/addon/toggle-document-design-mode/
https://addons.mozilla.org/en-US/firefox/addon/toggle-pin-tab/

you can ask them about the api's details/ or read our docs.(sorry a bit busy with Fx57)
or keep an eye on these.



https://bugzilla.mozilla.org/show_bug.cgi?id=116182
https://bugzilla.mozilla.org/show_bug.cgi?id=121347
https://bugzilla.mozilla.org/show_bug.cgi?id=121348
https://bugzilla.mozilla.org/show_bug.cgi?id=128363
https://bugzilla.mozilla.org/show_bug.cgi?id=119068
https://bugzilla.mozilla.org/show_bug.cgi?id=132971
https://bugzilla.mozilla.org/show_bug.cgi?id=133032
https://bugzilla.mozilla.org/show_bug.cgi?id=135141
https://bugzilla.mozilla.org/show_bug.cgi?id=133545
https://bugzilla.mozilla.org/show_bug.cgi?id=133657
https://bugzilla.mozilla.org/show_bug.cgi?id=121347
https://bugzilla.mozilla.org/show_bug.cgi?id=121099
https://bugzilla.mozilla.org/show_bug.cgi?id=122654
https://bugzilla.mozilla.org/show_bug.cgi?id=121185
https://bugzilla.mozilla.org/show_bug.cgi?id=56467
https://bugzilla.mozilla.org/show_bug.cgi?id=128036
https://bugzilla.mozilla.org/show_bug.cgi?id=121348


Cheers

**Comment by agenthardtofind** [comment]
>Well we are actively working on ways to bring all features to the new api, if you think anything is missing just file a bug , needinfo the triage owner or devs &

block

[meta] WebExtension requirements for 1&1 extensions

https://bugzilla.mozilla.org/show_bug.cgi?id=1333828

[meta] External bugs that webextensions depends on

https://bugzilla.mozilla.org/show_bug.cgi?id=1351411

[meta] Webextensions Development

Most of the things this ext does can be done easily with WE,helped a few devs to port fix this
like these:-
https://addons.mozilla.org/en-US/firefox/addon/popup-blocker/
https://addons.mozilla.org/en-US/firefox/addon/block-images-webextensions/
https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/
https://addons.mozilla.org/en-US/firefox/addon/mute-tab-webextension/
https://addons.mozilla.org/en-US/firefox/addon/javascript-toggler/
https://addons.mozilla.org/en-US/firefox/addon/javascript-toggle-on-and-off/
https://addons.mozilla.org/en-US/firefox/addon/toggle-document-design-mode/
https://addons.mozilla.org/en-US/firefox/addon/toggle-pin-tab/

you can ask them about the api's details/ or read our docs.(sorry a bit busy with Fx57)
or keep an eye on these.

https://bugzilla.mozilla.org/show_bug.cgi?id=116182
https://bugzilla.mozilla.org/show_bug.cgi?id=121347
https://bugzilla.mozilla.org/show_bug.cgi?id=121348
https://bugzilla.mozilla.org/show_bug.cgi?id=128363
https://bugzilla.mozilla.org/show_bug.cgi?id=119068
https://bugzilla.mozilla.org/show_bug.cgi?id=132971
https://bugzilla.mozilla.org/show_bug.cgi?id=133032
https://bugzilla.mozilla.org/show_bug.cgi?id=135141
https://bugzilla.mozilla.org/show_bug.cgi?id=133545
https://bugzilla.mozilla.org/show_bug.cgi?id=133657
https://bugzilla.mozilla.org/show_bug.cgi?id=121347
https://bugzilla.mozilla.org/show_bug.cgi?id=121099
https://bugzilla.mozilla.org/show_bug.cgi?id=122654
https://bugzilla.mozilla.org/show_bug.cgi?id=121185
https://bugzilla.mozilla.org/show_bug.cgi?id=56467
https://bugzilla.mozilla.org/show_bug.cgi?id=128036
https://bugzilla.mozilla.org/show_bug.cgi?id=121348

Cheers 

> 


Thanks for the good news :)
So most of the functions can be ported to WE right?


@ThatOneGuyDotNet  
 Bug 1357107 - Part 1: Move the handling of the permissions.default.image pref to imgLoader.cpp

This might land tomorrow and will it affect the QJ ext?

Like Bill said js button seems to work well , the other guy who told you to hack into every request does not appear to be there, might be he was misinformed or the api's were not there?

**Comment by agenthardtofind** [comment]
> Well we are actively working on ways to bring all features to the new api, if you think anything is > missing just file a bug , needinfo the triage owner or devs 
> 
> block
> 
> [meta] WebExtension requirements for 1&1 extensions
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1333828
> 
> [meta] External bugs that webextensions depends on
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1351411
> 
> [meta] Webextensions Development
> 
> Most of the things this ext does can be done easily with WE,helped a few devs to port fix this
> like these:-
> https://addons.mozilla.org/en-US/firefox/addon/popup-blocker/
> https://addons.mozilla.org/en-US/firefox/addon/block-images-webextensions/
> https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/
> https://addons.mozilla.org/en-US/firefox/addon/mute-tab-webextension/
> https://addons.mozilla.org/en-US/firefox/addon/javascript-toggler/
> https://addons.mozilla.org/en-US/firefox/addon/javascript-toggle-on-and-off/
> https://addons.mozilla.org/en-US/firefox/addon/toggle-document-design-mode/
> https://addons.mozilla.org/en-US/firefox/addon/toggle-pin-tab/
> 
> you can ask them about the api's details/ or read our docs.(sorry a bit busy with Fx57)
> or keep an eye on these.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=116182
> https://bugzilla.mozilla.org/show_bug.cgi?id=121347
> https://bugzilla.mozilla.org/show_bug.cgi?id=121348
> https://bugzilla.mozilla.org/show_bug.cgi?id=128363
> https://bugzilla.mozilla.org/show_bug.cgi?id=119068
> https://bugzilla.mozilla.org/show_bug.cgi?id=132971
> https://bugzilla.mozilla.org/show_bug.cgi?id=133032
> https://bugzilla.mozilla.org/show_bug.cgi?id=135141
> https://bugzilla.mozilla.org/show_bug.cgi?id=133545
> https://bugzilla.mozilla.org/show_bug.cgi?id=133657
> https://bugzilla.mozilla.org/show_bug.cgi?id=121347
> https://bugzilla.mozilla.org/show_bug.cgi?id=121099
> https://bugzilla.mozilla.org/show_bug.cgi?id=122654
> https://bugzilla.mozilla.org/show_bug.cgi?id=121185
> https://bugzilla.mozilla.org/show_bug.cgi?id=56467
> https://bugzilla.mozilla.org/show_bug.cgi?id=128036
> https://bugzilla.mozilla.org/show_bug.cgi?id=121348
> 
> Cheers 
> 


Thanks for the good news :)
So most of the functions can be ported to WE right?


@ThatOneGuyDotNet  
 Bug 1357107 - Part 1: Move the handling of the permissions.default.image pref to imgLoader.cpp

This might land tomorrow and will it affect the QJ ext?

Like Bill said js button seems to work well , the other guy who told you to hack into every request does not appear to be there, might be he was misinformed or the api's were not there?

**Comment by Gitoffthelawn** [comment]
Interested in learning the status.  No pressure. :)

**Comment by Gitoffthelawn** [comment]
Still interested in learning the status.  A touch of pressure as Firefox 57 deadline approaches.  :)

**Comment by ThatOneGuyDotNet** [comment]
As we get closer to the deadline the API's required to properly implement this add-on as a WebExtension are not yet completed.  Furthermore my personal life has been pretty insane lately (on top of work being busy, as usual).  I hate to say it guys but it's not looking like it's going to happen, this project may be dead :-/

**Comment by Gitoffthelawn** [comment]
Noooooooooooooooooooooooooooooooooooooooo!

:-)

I'm pretty sure there are JS and WebRTC togglers out there in WebExtensions, so that's definitely doable.

Toggling CSS might be a little tricky.

It seems like significant parts of it are workable in WebExtensions.

So here's the solution: Grow a mullet.  Your personal life will quickly dissipate.   One problem solved.  Quit your job.  Live off the land.  Besides, they don't want you and your mullet around any longer.  Two problems solved.  ;)

Remember, you have about 200,000 users depending on you growing that mullet... take one for the team... oh, and post photos.  ;)
