### ISSUE TITLE
New Version of FF is not supported  .

### ISSUE THREAD

**Issue by den812** [ThatOneGuyDotNet/QuickJava#49]
New Version of FF is not supported  .
 now FF is 57.0b2 x64

 Thank you so much for this addon

**Comment by FinnT730** [comment]
As far as I know it won't be updated anymore, but I may be wrong. The latest version build by the Devoleper was in 2016.

**Comment by ThatOneGuyDotNet** [comment]
The post above is correct. Not sure why I didn't see the email notification when the original comment was posted. My apologies.

More information can be found:
http://quickjavaplugin.blogspot.com/2017/10/quickjava-to-be-obsolete-with-firefox.html
